### ISSUE TITLE
CI: http integration testing failure

### ISSUE THREAD

**Issue by vincenzopalazzo** [coffee-tools/coffee#208]
```
2023-10-12T19:08:14.8401429Z [36mcoffee_1  |[0m ---- coffee_httpd_integration_tests::httpd_init_add_remote stdout ----
2023-10-12T19:08:14.8402659Z [36mcoffee_1  |[0m thread '<unnamed>' panicked at tests/src/coffee_httpd_integration_tests.rs:66:10:
2023-10-12T19:08:14.8404338Z [36mcoffee_1  |[0m called `Result::unwrap()` on an `Err` value: Rpc(RpcError { code: -32601, message: "Unknown command 'summary'", data: None })
2023-10-12T19:08:14.8405713Z [36mcoffee_1  |[0m stack backtrace:
2023-10-12T19:08:14.8406267Z [36mcoffee_1  |[0m    0: rust_begin_unwind
2023-10-12T19:08:14.8407588Z [36mcoffee_1  |[0m              at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
2023-10-12T19:08:14.8408688Z [36mcoffee_1  |[0m    1: core::panicking::panic_fmt
2023-10-12T19:08:14.8409797Z [36mcoffee_1  |[0m              at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
2023-10-12T19:08:14.8410869Z [36mcoffee_1  |[0m    2: core::result::unwrap_failed
2023-10-12T19:08:14.8411965Z [36mcoffee_1  |[0m              at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1652:5
2023-10-12T19:08:14.8413060Z [36mcoffee_1  |[0m    3: core::result::Result<T,E>::unwrap
2023-10-12T19:08:14.8414168Z [36mcoffee_1  |[0m              at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1077:23
2023-10-12T19:08:14.8415629Z [36mcoffee_1  |[0m    4: tests::coffee_httpd_integration_tests::httpd_init_add_remote::ntest_callback::{{closure}}
2023-10-12T19:08:14.8416794Z [36mcoffee_1  |[0m              at ./src/coffee_httpd_integration_tests.rs:64:5
2023-10-12T19:08:14.8417800Z [36mcoffee_1  |[0m    5: <core::pin::Pin<P> as core::future::future::Future>::poll
2023-10-12T19:08:14.8419081Z [36mcoffee_1  |[0m              at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/future/future.rs:125:9
2023-10-12T19:08:14.8420385Z [36mcoffee_1  |[0m    6: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
2023-10-12T19:08:14.8421815Z [36mcoffee_1  |[0m              at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/park.rs:283:63
2023-10-12T19:08:14.8423035Z [36mcoffee_1  |[0m    7: tokio::runtime::coop::with_budget
2023-10-12T19:08:14.8424286Z [36mcoffee_1  |[0m              at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/coop.rs:107:5
2023-10-12T19:08:14.8425477Z [36mcoffee_1  |[0m    8: tokio::runtime::coop::budget
2023-10-12T19:08:14.8426851Z [36mcoffee_1  |[0m              at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/coop.rs:73:5
2023-10-12T19:08:14.8428178Z [36mcoffee_1  |[0m    9: tokio::runtime::park::CachedParkThread::block_on
2023-10-12T19:08:14.8429530Z [36mcoffee_1  |[0m              at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/park.rs:283:31
2023-10-12T19:08:14.8430963Z [36mcoffee_1  |[0m   10: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
2023-10-12T19:08:14.8432475Z [36mcoffee_1  |[0m              at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/context/blocking.rs:66:9
2023-10-12T19:08:14.8434049Z [36mcoffee_1  |[0m   11: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}
2023-10-12T19:08:14.8435741Z [36mcoffee_1  |[0m              at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/multi_thread/mod.rs:87:13
2023-10-12T19:08:14.8437206Z [36mcoffee_1  |[0m   12: tokio::runtime::context::runtime::enter_runtime
2023-10-12T19:08:14.8438616Z [36mcoffee_1  |[0m              at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/context/runtime.rs:65:16
2023-10-12T19:08:14.8440110Z [36mcoffee_1  |[0m   13: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
2023-10-12T19:08:14.8441711Z [36mcoffee_1  |[0m              at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/scheduler/multi_thread/mod.rs:86:9
2023-10-12T19:08:14.8443149Z [36mcoffee_1  |[0m   14: tokio::runtime::runtime::Runtime::block_on
2023-10-12T19:08:14.8444474Z [36mcoffee_1  |[0m              at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/runtime.rs:313:45
2023-10-12T19:08:14.8518051Z [36mcoffee_1  |[0m   15: tests::coffee_httpd_integration_tests::httpd_init_add_remote::ntest_callback
2023-10-12T19:08:14.8519205Z [36mcoffee_1  |[0m              at ./src/coffee_httpd_integration_tests.rs:68:5
2023-10-12T19:08:14.8520646Z [36mcoffee_1  |[0m   16: tests::coffee_httpd_integration_tests::httpd_init_add_remote::{{closure}}
2023-10-12T19:08:14.8521779Z [36mcoffee_1  |[0m              at ./src/coffee_httpd_integration_tests.rs:10:1
2023-10-12T19:08:14.8522968Z [36mcoffee_1  |[0m note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
2023-10-12T19:08:14.8524953Z [36mcoffee_1  |[0m thread 'coffee_httpd_integration_tests::httpd_init_add_remote' panicked at tests/src/coffee_httpd_integration_tests.rs:10:1:
2023-10-12T19:08:14.8526121Z [36mcoffee_1  |[0m explicit panic
2023-10-12T19:08:14.8529703Z [36mcoffee_1  |[0m stack backtrace:
2023-10-12T19:08:14.8530536Z [36mcoffee_1  |[0m    0: std::panicking::begin_panic
2023-10-12T19:08:14.8531666Z [36mcoffee_1  |[0m              at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:627:12
2023-10-12T19:08:14.8532974Z [36mcoffee_1  |[0m    1: tests::coffee_httpd_integration_tests::httpd_init_add_remote
2023-10-12T19:08:14.8533980Z [36mcoffee_1  |[0m              at ./src/coffee_httpd_integration_tests.rs:10:1
2023-10-12T19:08:14.8535092Z [36mcoffee_1  |[0m    2: tests::coffee_httpd_integration_tests::httpd_init_add_remote::{{closure}}
2023-10-12T19:08:14.8536173Z [36mcoffee_1  |[0m              at ./src/coffee_httpd_integration_tests.rs:11:38
2023-10-12T19:08:14.8537082Z [36mcoffee_1  |[0m    3: core::ops::function::FnOnce::call_once
2023-10-12T19:08:14.8538268Z [36mcoffee_1  |[0m              at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
2023-10-12T19:08:14.8539415Z [36mcoffee_1  |[0m    4: core::ops::function::FnOnce::call_once
2023-10-12T19:08:14.8540589Z [36mcoffee_1  |[0m              at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:250:5
2023-10-12T19:08:14.8542270Z [36mcoffee_1  |[0m note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
2023-10-12T19:08:14.8544121Z [36mcoffee_1  |[0m 
2023-10-12T19:08:14.8544513Z [36mcoffee_1  |[0m 
```

Unrelated failure but we should debug it @tareknaser

_Originally posted by @vincenzopalazzo in https://github.com/coffee-tools/coffee/issues/207#issuecomment-1760273746_

**Comment by vincenzopalazzo** [comment]
Looks like that the error is related to the python package 

```
coffee_1  | 2023-10-12T19:07:25.798Z DEBUG hyper::proto::h1::io flushed 153 bytes
coffee_1  | 2023-10-12T19:07:25.926Z DEBUG hyper::proto::h1::io parsed 2 headers
coffee_1  | 2023-10-12T19:07:25.926Z DEBUG hyper::proto::h1::conn incoming body is content-length (42 bytes)
coffee_1  | 2023-10-12T19:07:25.926Z DEBUG hyper::proto::h1::conn incoming body completed
coffee_1  | 2023-10-12T19:07:25.926Z DEBUG hyper::client::pool pooling idle connection for ("http", 127.0.0.1:39185)
coffee_1  | 2023-10-12T19:07:25.927Z INFO tests::coffee_httpd_integration_tests /remote/add response: Repository 'lightningd' added successfully
coffee_1  | 2023-10-12T19:07:25.929Z DEBUG hyper::client::pool reuse idle connection for ("http", 127.0.0.1:39185)
coffee_1  | 2023-10-12T19:07:25.929Z DEBUG hyper::proto::h1::io flushed 154 bytes
coffee_1  | 2023-10-12T19:07:28.454Z DEBUG hyper::proto::h1::io parsed 3 headers
coffee_1  | 2023-10-12T19:07:28.454Z DEBUG hyper::proto::h1::conn incoming body is content-length (198 bytes)
coffee_1  | 2023-10-12T19:07:28.455Z DEBUG hyper::proto::h1::conn incoming body completed
coffee_1  | 2023-10-12T19:07:28.456Z DEBUG hyper::client::pool pooling idle connection for ("http", 127.0.0.1:43951)
coffee_1  | 2023-10-12T19:07:28.456Z INFO tests::coffee_httpd_integration_tests /install response: Error: code: 2, msg: ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/_cffi_backend.cpython-38-x86_64-linux-gnu.so'
coffee_1  | 
coffee_1  | 
```

Needs more looking into it
